import type { SectionConfig } from "@/components/admin/SectionEditor";

/**
 * Section configurations for the admin CMS.
 * Each entry maps a URL slug to its database key and editable fields.
 */
export const SECTION_CONFIGS: Record<string, SectionConfig> = {
  hero: {
    key: "hero",
    title: "Hero",
    description:
      "The main hero banner with background video, heading, and call-to-action buttons.",
    publicPath: "/",
    fields: [
      { name: "badge", label: "Badge Text", type: "text" },
      { name: "heading", label: "Heading Line 1", type: "text" },
      { name: "headingHighlight", label: "Heading Line 2 (Gold)", type: "text" },
      { name: "description", label: "Description", type: "textarea" },
      { name: "ctaPrimary", label: "Primary Button Text", type: "text" },
      { name: "ctaPrimaryLink", label: "Primary Button Link", type: "text" },
      { name: "ctaSecondary", label: "Secondary Button Text", type: "text" },
      {
        name: "video",
        label: "Background Video",
        type: "media",
        uploadFolder: "hero",
        preview: true,
      },
      {
        name: "poster",
        label: "Poster Image",
        type: "media",
        uploadFolder: "hero",
        preview: true,
      },
    ],
  },
  about: {
    key: "about",
    title: "About",
    description:
      "About section with video, mission text, and the three teaching pillars.",
    publicPath: "/#about",
    fields: [
      { name: "label", label: "Section Label", type: "text" },
      { name: "title", label: "Title Line 1", type: "text" },
      { name: "titleHighlight", label: "Title Line 2 (Gold)", type: "text" },
      { name: "description", label: "First Paragraph", type: "textarea" },
      { name: "description2", label: "Second Paragraph", type: "textarea" },
      {
        name: "video",
        label: "About Video",
        type: "media",
        uploadFolder: "about",
        preview: true,
      },
      {
        name: "poster",
        label: "Video Poster Image",
        type: "media",
        uploadFolder: "about",
        preview: true,
      },
      { name: "videoLabel", label: "Video Bottom Label", type: "text" },
      { name: "cta", label: "CTA Button Text", type: "text" },
      { name: "ctaLink", label: "CTA Button Link", type: "text" },
      { name: "pillar1Label", label: "Pillar 1 Label", type: "text" },
      { name: "pillar1Desc", label: "Pillar 1 Description", type: "text" },
      { name: "pillar2Label", label: "Pillar 2 Label", type: "text" },
      { name: "pillar2Desc", label: "Pillar 2 Description", type: "text" },
      { name: "pillar3Label", label: "Pillar 3 Label", type: "text" },
      { name: "pillar3Desc", label: "Pillar 3 Description", type: "text" },
    ],
  },
  "career-path": {
    key: "career_path",
    title: "Career Path",
    description:
      "Career path section showing the 4 learning steps from beginner to work-ready.",
    publicPath: "/#career-path",
    fields: [
      { name: "title", label: "Title Line 1", type: "text" },
      { name: "titleHighlight", label: "Title Line 2 (Gold)", type: "text" },
      { name: "subtitle", label: "Subtitle", type: "textarea" },
      { name: "step1Label", label: "Step 1 Label", type: "text" },
      { name: "step1Desc", label: "Step 1 Description", type: "textarea" },
      { name: "step2Label", label: "Step 2 Label", type: "text" },
      { name: "step2Desc", label: "Step 2 Description", type: "textarea" },
      { name: "step3Label", label: "Step 3 Label", type: "text" },
      { name: "step3Desc", label: "Step 3 Description", type: "textarea" },
      { name: "step4Label", label: "Step 4 Label", type: "text" },
      { name: "step4Desc", label: "Step 4 Description", type: "textarea" },
      { name: "note", label: "Bottom Note", type: "textarea" },
    ],
  },
  "what-we-teach": {
    key: "what_we_teach",
    title: "What We Teach",
    description:
      "Feature grid showcasing the four core disciplines taught at the academy.",
    publicPath: "/#what-we-teach",
    fields: [
      { name: "eyebrow", label: "Eyebrow Text", type: "text" },
      { name: "heading", label: "Heading", type: "text" },
      { name: "subtitle", label: "Subtitle", type: "textarea" },
      { name: "item1Title", label: "Item 1 Title", type: "text" },
      { name: "item1Desc", label: "Item 1 Description", type: "textarea" },
      { name: "item2Title", label: "Item 2 Title", type: "text" },
      { name: "item2Desc", label: "Item 2 Description", type: "textarea" },
      { name: "item3Title", label: "Item 3 Title", type: "text" },
      { name: "item3Desc", label: "Item 3 Description", type: "textarea" },
      { name: "item4Title", label: "Item 4 Title", type: "text" },
      { name: "item4Desc", label: "Item 4 Description", type: "textarea" },
    ],
  },
  "featured-courses": {
    key: "featured_courses",
    title: "Featured Courses",
    description:
      "Course cards section with heading and view-all link. Course data lives in src/data/courses.ts.",
    publicPath: "/#courses",
    fields: [
      { name: "eyebrow", label: "Eyebrow Text", type: "text" },
      { name: "heading", label: "Heading", type: "text" },
      { name: "subtitle", label: "Subtitle", type: "textarea" },
      { name: "viewAll", label: "View All Link Text", type: "text" },
    ],
  },
  programs: {
    key: "programs",
    title: "Programs",
    description:
      "Programs section heading and subtitle.",
    publicPath: "/#courses",
    fields: [
      { name: "title", label: "Section Title", type: "text" },
      { name: "subtitle", label: "Section Subtitle", type: "text" },
      { name: "cta", label: "Learn More Button Text", type: "text" },
    ],
  },
  "why-nalik": {
    key: "founder",
    title: "Why Nalik Academy",
    description:
      "Founder story section explaining why students should choose Nalik Academy.",
    publicPath: "/#about",
    fields: [
      { name: "label", label: "Section Label", type: "text" },
      { name: "title", label: "Title Line 1", type: "text" },
      { name: "titleHighlight", label: "Title Line 2 (Gold)", type: "text" },
      { name: "description", label: "First Paragraph", type: "textarea" },
      { name: "description2", label: "Second Paragraph", type: "textarea" },
      {
        name: "video",
        label: "Founder Video",
        type: "media",
        uploadFolder: "founder",
        preview: true,
      },
      { name: "cta", label: "CTA Button Text", type: "text" },
      { name: "highlight1", label: "Highlight 1", type: "text" },
      { name: "highlight2", label: "Highlight 2", type: "text" },
      { name: "highlight3", label: "Highlight 3", type: "text" },
      { name: "highlight4", label: "Highlight 4", type: "text" },
    ],
  },
  "learning-process": {
    key: "learning_process",
    title: "Learning Process",
    description:
      "How You Learn section with 4 learning steps and bottom note.",
    publicPath: "/#courses",
    fields: [
      { name: "title", label: "Title Line 1", type: "text" },
      { name: "titleHighlight", label: "Title Line 2 (Gold)", type: "text" },
      { name: "subtitle", label: "Subtitle", type: "textarea" },
      { name: "step1Label", label: "Step 1 Label", type: "text" },
      { name: "step1Desc", label: "Step 1 Description", type: "textarea" },
      { name: "step2Label", label: "Step 2 Label", type: "text" },
      { name: "step2Desc", label: "Step 2 Description", type: "textarea" },
      { name: "step3Label", label: "Step 3 Label", type: "text" },
      { name: "step3Desc", label: "Step 3 Description", type: "textarea" },
      { name: "step4Label", label: "Step 4 Label", type: "text" },
      { name: "step4Desc", label: "Step 4 Description", type: "textarea" },
      { name: "note", label: "Bottom Note", type: "textarea" },
    ],
  },
  contact: {
    key: "contact",
    title: "Contact Settings",
    description:
      "Contact information, phone, email, location, and social media links.",
    publicPath: "/#contact",
    fields: [
      { name: "title", label: "Section Title", type: "text" },
      { name: "subtitle", label: "Section Subtitle", type: "textarea" },
      { name: "phone", label: "Phone Number", type: "text" },
      { name: "whatsapp", label: "WhatsApp Number", type: "text" },
      {
        name: "whatsappMessage",
        label: "WhatsApp Default Message",
        type: "text",
      },
      { name: "email", label: "Email Address", type: "text" },
      { name: "location", label: "Location", type: "text" },
      { name: "instagram", label: "Instagram URL", type: "text" },
      { name: "tiktok", label: "TikTok URL", type: "text" },
      { name: "facebook", label: "Facebook URL", type: "text" },
      {
        name: "formRecipientEmail",
        label: "Form Recipient Email",
        type: "text",
      },
    ],
  },
  "final-cta": {
    key: "final_cta",
    title: "Final CTA",
    description:
      "Final call-to-action section at the bottom of the homepage.",
    publicPath: "/",
    fields: [
      { name: "heading", label: "Heading", type: "text" },
      { name: "description", label: "Description", type: "textarea" },
      { name: "cta", label: "Button Text", type: "text" },
      {
        name: "video",
        label: "Background Video",
        type: "media",
        uploadFolder: "cta",
        preview: true,
      },
      {
        name: "poster",
        label: "Poster Image",
        type: "media",
        uploadFolder: "cta",
        preview: true,
      },
    ],
  },
};
